### ISSUE TITLE
[Colab] cannot import name 'filter2d' from 'kornia'

### ISSUE THREAD

**Issue by katongo** [lucidrains/lightweight-gan#102]
Hi

Training on google Colab Pro, I started getting this error:

Traceback (most recent call last):
  File "/usr/local/bin/lightweight_gan", line 5, in <module>
    from lightweight_gan.cli import main
  File "/usr/local/lib/python3.7/dist-packages/lightweight_gan/__init__.py", line 1, in <module>
    from lightweight_gan.lightweight_gan import LightweightGAN, Generator, Discriminator, Trainer, NanException
  File "/usr/local/lib/python3.7/dist-packages/lightweight_gan/lightweight_gan.py", line 25, in <module>
    from kornia import filter2d
ImportError: cannot import name 'filter2d' from 'kornia' (/usr/local/lib/python3.7/dist-packages/kornia/__init__.py)

Before that everything worked fine for several weeks

**Comment by CaptainStabs** [comment]
This was fixed with the latest release

**Comment by domef** [comment]
I'm having the same problem, I fixed it by changing https://github.com/lucidrains/lightweight-gan/blob/fce20938562a0cc289c915f7317722a8241abd37/lightweight_gan/lightweight_gan.py#L25 in `from kornia.filters import filter2d`.
