### ISSUE TITLE
ImportError: cannot import name 'filter2d' from 'kornia'

### ISSUE THREAD

**Issue by Technerder** [lucidrains/lightweight-gan#111]
Trying to use `lightweight-gan` in a Google Colab notebook but I'm running into this issue.

```error
Traceback (most recent call last):
  File "/usr/local/bin/lightweight_gan", line 5, in <module>
    from lightweight_gan.cli import main
  File "/usr/local/lib/python3.7/dist-packages/lightweight_gan/__init__.py", line 1, in <module>
    from lightweight_gan.lightweight_gan import LightweightGAN, Generator, Discriminator, Trainer, NanException
  File "/usr/local/lib/python3.7/dist-packages/lightweight_gan/lightweight_gan.py", line 25, in <module>
    from kornia import filter2d
ImportError: cannot import name 'filter2d' from 'kornia' (/usr/local/lib/python3.7/dist-packages/kornia/__init__.py)
````

Installed using `pip install lightweight-gan`

**Comment by domef** [comment]
In fixed it in this way https://github.com/lucidrains/lightweight-gan/issues/102#issuecomment-1013700520.

**Comment by lucidrains** [comment]
let me know if 0.20.7 works!

**Comment by domef** [comment]
Now it works, thank you.
