### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hparams'

### ISSUE THREAD

**Issue by sebastiantrella** [lucidrains/lightweight-gan#123]
since today I am getting an error when resuming training.

Traceback (most recent call last):
  File "/opt/conda/bin/lightweight_gan", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/cli.py", line 193, in main
    fire.Fire(train_from_folder)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/cli.py", line 184, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name, seed, use_aim, aim_repo, aim_run_hash)
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/cli.py", line 59, in run_training
    model.load(load_from)
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/lightweight_gan.py", line 1448, in load
    self.load_config()
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/lightweight_gan.py", line 1035, in load_config
    self.init_GAN()
  File "/opt/conda/lib/python3.8/site-packages/lightweight_gan/lightweight_gan.py", line 996, in init_GAN
    self.GAN = LightweightGAN(
TypeError: __init__() got an unexpected keyword argument 'hparams'

**Comment by sebastiantrella** [comment]
Could fix it myself. Had to clean up old scripts in my environment. Sorry!
