### ISSUE TITLE
Aim installation error

### ISSUE THREAD

**Issue by demiahmed** [lucidrains/lightweight-gan#132]
I'm trying to run the generator after training, to generate fake samples using the following command

```lightweight_gan --generate --load-from 299```

I get this following error: 

```
Traceback (most recent call last):
  File "C:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\anaconda3\Scripts\lightweight_gan.exe\__main__.py", line 7, in <module>
  File "C:\anaconda3\lib\site-packages\lightweight_gan\cli.py", line 195, in main
    fire.Fire(train_from_folder)
  File "C:\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\anaconda3\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\anaconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\anaconda3\lib\site-packages\lightweight_gan\cli.py", line 158, in train_from_folder
    model = Trainer(**model_args)
  File "C:\anaconda3\lib\site-packages\lightweight_gan\lightweight_gan.py", line 1057, in __init__
    self.run = self.aim.Run(run_hash=aim_run_hash, repo=aim_repo)
AttributeError: 'Trainer' object has no attribute 'aim'
```

and when I try to run ```pip install aim```, I get a dependency error with ```aimrocks```

```
  ERROR: Command errored out with exit status 1:
   command: 'C:\Anaconda3\envs\aerialweb\python.exe' 'C:\Anaconda3\envs\aerialweb\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\ahmed\AppData\Local\Temp\pip-build-env-b2ysw94t\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython >= 3.0.0a9' 'aimrocks == 0.2.1'
       cwd: None
  Complete output (12 lines):
  WARNING: Ignoring invalid distribution -pencv-python (c:\anaconda3\envs\aerialweb\lib\site-packages)
  WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\envs\aerialweb\lib\site-packages)
  Collecting setuptools
    Using cached setuptools-59.6.0-py3-none-any.whl (952 kB)
  Collecting cython>=3.0.0a9
    Using cached Cython-3.0.0a10-py2.py3-none-any.whl (1.1 MB)
  ERROR: Could not find a version that satisfies the requirement aimrocks==0.2.1 (from versions: 0.1.3a14, 0.2.0.dev1, 0.2.0)
  ERROR: No matching distribution found for aimrocks==0.2.1
  WARNING: Ignoring invalid distribution -pencv-python (c:\anaconda3\envs\aerialweb\lib\site-packages)
  WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\envs\aerialweb\lib\site-packages)
  WARNING: Ignoring invalid distribution -pencv-python (c:\anaconda3\envs\aerialweb\lib\site-packages)
  WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\envs\aerialweb\lib\site-packages)
```

What is ```aimrocks``` and what does it actually do? I am unable to find a matching distribution or even a wheel file to install it manually. Please help

**Comment by rgaiacs** [comment]
I'm having the same issue.

**Comment by rgaiacs** [comment]
@demiahmed what version of Python are you using? `pip install aim` worked with 3.10.4.

**Comment by lino-levan** [comment]
Aim cannot be installed on windows. Very unfortunate.

**Comment by deadSwank001** [comment]
> 

I'm getting a successful install up to 3.7.3, then yeah it just gets stuck.
