### ISSUE TITLE
`pip install lightweight-gan` not working. ERROR: Command errored out with exit status 1: python setup.py egg_info

### ISSUE THREAD

**Issue by Dok11** [lucidrains/lightweight-gan#16]
I tried it several times on my pc with win10 and every time i got error:
```
(lightweight-gan) E:\Projects\lightweight-gan>pip install lightweight-gan
Collecting lightweight-gan
  Using cached lightweight_gan-0.12.3-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.12.2-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.12.1-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.12.0-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.11.3-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.11.2-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.11.1-py3-none-any.whl (27 kB)
  Using cached lightweight_gan-0.11.0-py3-none-any.whl (27 kB)
Collecting adabelief-pytorch
  Using cached adabelief_pytorch-0.1.0-py3-none-any.whl (5.5 kB)
  Using cached adabelief_pytorch-0.0.5-py3-none-any.whl (4.8 kB)
INFO: pip is looking at multiple versions of lightweight-gan to determine which version is compatible with other requirements. This could take a while.
Collecting lightweight-gan
  Using cached lightweight_gan-0.10.0-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.9.2-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.9.1-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.9.0-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.8.5-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.8.4-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.8.3-py3-none-any.whl (26 kB)
INFO: pip is looking at multiple versions of lightweight-gan to determine which version is compatible with other requirements. This could take a while.
  Using cached lightweight_gan-0.8.2-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.8.0-py3-none-any.whl (26 kB)
  Using cached lightweight_gan-0.7.9-py3-none-any.whl (25 kB)
  Using cached lightweight_gan-0.7.8-py3-none-any.whl (25 kB)
  Using cached lightweight_gan-0.7.7-py3-none-any.whl (25 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached lightweight_gan-0.7.6-py3-none-any.whl (25 kB)
Collecting einops>=0.3
  Using cached einops-0.3.0-py2.py3-none-any.whl (25 kB)
Collecting fire
  Using cached fire-0.3.1.tar.gz (81 kB)
Collecting hamburger-pytorch
  Using cached hamburger_pytorch-0.0.3-py3-none-any.whl (3.4 kB)
Collecting numpy
  Downloading numpy-1.19.4-cp36-cp36m-win_amd64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 6.8 MB/s
Collecting pillow
  Downloading Pillow-8.0.1-cp36-cp36m-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.4 MB/s
Collecting pytorch-fid
  Using cached pytorch-fid-0.2.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-maq6gjoa\\pytorch-fid_ef9965f93e55457790c769e9b5008169\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-maq6gjoa\\pytorch-fid_ef9965f93e55457790c769e9b5008169\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'
\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-weq0pjeo'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-maq6gjoa\pytorch-fid_ef9965f93e55457790c769e9b5008169\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-maq6gjoa\pytorch-fid_ef9965f93e55457790c769e9b5008169\setup.py", line 34, in <module>
        packages=setuptools.find_packages(where='src/'),
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Seems like pip tried use env in system dir of anaconda, but I have virtualenv in the project folder. I successfully executed this commands:
```
conda create --prefix E:\Projects\lightweight-gan\env python=3.9.0
conda activate E:\Projects\lightweight-gan\env
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```

Have you some ideas what I can do with this error?

**Comment by trufty** [comment]
There was a windows compatibility issue in the pytorch-fid repo.  They fixed it, but not sure when it will be available in pip.  
For now you can download their repo and run `python setup.py install` from the downloaded /pytorch-fid-master directory to install it locally.  Then you should be able to do `pip install lightweight-gan`

**Comment by Dok11** [comment]
After some research I think what I need clone repo, but not install as package.

**Comment by sharpe5** [comment]
Issue is PyTorch under Windows. For a workaround, see same issue here:
https://github.com/lucidrains/stylegan2-pytorch/issues/178

**Comment by Dok11** [comment]
So installation which working for me (win 10) contain in these steps:
1. Create folder for project
2. `git clone https://github.com/lucidrains/lightweight-gan.git`
3. Creating new env
4. `conda activate`
5. `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`
6. `python -m pip install git+https://github.com/mseitzer/pytorch-fid.git@732341f2129bc8b41cbbfaa4d738788645cb1df7`
7. `pip install -e \path\to\project\lightweight-gan` (clonned folder)
