### ISSUE TITLE
Do I need Nvidia GPU with CUDA to generate images from a model?

### ISSUE THREAD

**Issue by arispen** [lucidrains/lightweight-gan#19]
When trying to generate images from trained model I get the error:

```/home/user/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/magic/.local/bin/lightweight_gan", line 5, in <module>
    from lightweight_gan.cli import main
  File "/home/magic/.local/lib/python3.8/site-packages/lightweight_gan/__init__.py", line 1, in <module>
    from lightweight_gan.lightweight_gan import LightweightGAN, Generator, Discriminator, Trainer, NanException
  File "/home/magic/.local/lib/python3.8/site-packages/lightweight_gan/lightweight_gan.py", line 41, in <module>
    assert torch.cuda.is_available(), 'You need to have an Nvidia GPU with CUDA installed.'
AssertionError: You need to have an Nvidia GPU with CUDA installed.
```

Do I really need Nvidia card to generate images from pre-trained model? I wanted to generate images in my VPS as a web service...

**Comment by lucidrains** [comment]
@arispen yes you do unfortunately

**Comment by drn1998** [comment]
Why though? There is nothing a GPU can do a CPU fundamentally cannot, it's just a matter of render time and if you want to be forced to use NVIDIAs proprietary drivers.
