### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by happypycode** [lucidrains/lightweight-gan#34]
``
C:\Users\Lenovo>pip install lightweight-gan
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://pypi.douban.com/simple
Collecting lightweight-gan
  Downloading http://pypi.doubanio.com/packages/3b/be/3cc7cf30cb6c121d323d2effc5758a24f464774a5919adb4308315860516/lightweight_gan-0.14.1-py3-none-any.whl (28 kB)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\roaming\python\python36\site-packages (from lightweight-gan) (1.18.3)
Requirement already satisfied: torchvision in c:\programdata\anaconda3\lib\site-packages (from lightweight-gan) (0.6.0+cpu)
Requirement already satisfied: tqdm in c:\users\lenovo\appdata\roaming\python\python36\site-packages (from lightweight-gan) (4.45.0)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from lightweight-gan) (1.4.1)
Collecting einops>=0.3
  Downloading http://pypi.doubanio.com/packages/5d/a0/9935e030634bf60ecd572c775f64ace82ceddf2f504a5fd3902438f07090/einops-0.3.0-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pillow in c:\users\lenovo\appdata\roaming\python\python36\site-packages (from lightweight-gan) (6.0.0)
Collecting gsa-pytorch
  Downloading http://pypi.doubanio.com/packages/f5/d9/edcfbc07155cf8c9757728e7a46077f0387786bdde07cffc14ad06ea790b/gsa_pytorch-0.2.2-py3-none-any.whl (3.6 kB)
Collecting retry
  Downloading http://pypi.doubanio.com/packages/4b/0d/53aea75710af4528a25ed6837d71d117602b01946b307a3912cb3cfcbcba/retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Collecting fire
  Downloading http://pypi.doubanio.com/packages/34/a7/0e22e70778aca01a52b9c899d9c145c6396d7b613719cd63db97ffa13f2f/fire-0.3.1.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 1.3 MB/s
Collecting kornia
  Downloading http://pypi.doubanio.com/packages/25/f6/9fb4cc2c67796680c8041fa6ffdee5f280e4cf65c86835768a700a324d59/kornia-0.4.1-py2.py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 226 kB/s
Collecting pytorch-fid
  Downloading http://pypi.doubanio.com/packages/93/54/49dc21a5ee774af0390813c3cf66af57af0a31ab22ba0c2ac02cdddeb755/pytorch-fid-0.2.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-d1z9rk7k\\pytorch-fid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-d1z9rk7k\\pytorch-fid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Lenovo\AppData\Local\Temp\pip-pip-egg-info-7fajsvz9'
         cwd: C:\Users\Lenovo\AppData\Local\Temp\pip-install-d1z9rk7k\pytorch-fid\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-install-d1z9rk7k\pytorch-fid\setup.py", line 34, in <module>
        packages=setuptools.find_packages(where='src/'),
      File "C:\Users\Lenovo\AppData\Roaming\Python\Python36\site-packages\setuptools\__init__.py", line 71, in find
        convert_path(where),
      File "C:\ProgramData\Anaconda3\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
``

**Comment by woctezuma** [comment]
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

**Comment by lucidrains** [comment]
hey! do you want to give 0.14.3 a try?

**Comment by electroram** [comment]
I have the same problem, too.

Collecting pytorch-fid==0.2.0
  Using cached pytorch-fid-0.2.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\software\anaconda3\envs\kinetic_gan\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lry\\AppData\\Local\\Temp\\pip-install-pmx18ptb\\pytorch-fid\\setup.py'"'"'; __file__='"'"'C:\\Users\\lry\\AppData\\Local\\Temp\\pip-install-pmx18ptb\\pytorch-fid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lry\AppData\Local\Temp\pip-pip-egg-info-h4l0of94'
         cwd: C:\Users\lry\AppData\Local\Temp\pip-install-pmx18ptb\pytorch-fid\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lry\AppData\Local\Temp\pip-install-pmx18ptb\pytorch-fid\setup.py", line 34, in <module>
        packages=setuptools.find_packages(where='src/'),
      File "d:\software\anaconda3\envs\kinetic_gan\lib\site-packages\setuptools\discovery.py", line 113, in find
        convert_path(str(where)),
      File "d:\software\anaconda3\envs\kinetic_gan\lib\site-packages\setuptools\_distutils\util.py", line 141, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
