### ISSUE TITLE
Unable to use "Show Progress"

### ISSUE THREAD

**Issue by bckwalton** [lucidrains/lightweight-gan#49]
Summary:  Running `lightweight_gan --models_dir "path" --show-progress ` results in a `AttributeError: 'NoneType' object has no attribute 'split'`

Full error: 
`Generating progress images:   0% 0/30 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/lightweight_gan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 185, in main
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 166, in train_from_folder
    model.show_progress(num_images=num_image_tiles, types=generate_types)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1217, in show_progress
    generated_image = self.generate_truncated(self.GAN.G, latents)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1272, in generate_truncated
    generated_images = evaluate_in_chunks(self.batch_size, G, style)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 99, in evaluate_in_chunks
    split_args = list(zip(*list(map(lambda x: x.split(max_batch_size, dim=0), args))))
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 99, in <lambda>
    split_args = list(zip(*list(map(lambda x: x.split(max_batch_size, dim=0), args))))
AttributeError: 'NoneType' object has no attribute 'split'
`

I've tried populating all the fields listed in the readme just to check with no luck.

**Comment by Dok11** [comment]
Try this: `lightweight_gan --name name-of-your-model --show-progress --num-image-tiles 4 --generate-types [ema]`
Linrary dont support `--models_dir "path"` argument.

**Comment by bckwalton** [comment]
Unfortunately no dice. Different error this time though.
Ran: `!lightweight_gan --name "default" --show-progress --num-image-tiles 4 --generate-types [ema]`
Log: `
Generating progress images: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/lightweight_gan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 185, in main
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 166, in train_from_folder
    model.show_progress(num_images=num_image_tiles, types=generate_types)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1208, in show_progress
    for checkpoint in tqdm(checkpoints, desc='Generating progress images'):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable
Generating progress images: 0it [00:00, ?it/s]
`

**Comment by woctezuma** [comment]
Issue arises here:

https://github.com/lucidrains/lightweight-gan/blob/359c868ec8eddd83b200e31b49f88501cbff674c/lightweight_gan/lightweight_gan.py#L1197-L1210

It looks like:

**Comment by bckwalton** [comment]
Currently running the latest (0.17.4). Worth noting that this is running in Colab, not sure why it would cause this but I'd be remiss to not mention this.

**Comment by bckwalton** [comment]
Dang it, I was pretty sure I had it there. With models_dir being unsupported here, I figured it was unable to find the checkpoints since it checks ./models/model-name/ but in my environment, the checkpoints are in ./model-name/. Moved the folders around... Now I'm back to the first error. 

`
Generating progress images:   0% 0/32 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/lightweight_gan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 185, in main
    fire.Fire(train_from_folder)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/cli.py", line 166, in train_from_folder
    model.show_progress(num_images=num_image_tiles, types=generate_types)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1223, in show_progress
    generated_image = self.generate_truncated(self.GAN.GE, latents)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1272, in generate_truncated
    generated_images = evaluate_in_chunks(self.batch_size, G, style)
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 99, in evaluate_in_chunks
    split_args = list(zip(*list(map(lambda x: x.split(max_batch_size, dim=0), args))))
  File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 99, in <lambda>
    split_args = list(zip(*list(map(lambda x: x.split(max_batch_size, dim=0), args))))
AttributeError: 'NoneType' object has no attribute 'split'
Generating progress images:   0% 0/32 [00:12<?, ?it/s]
`

Ther number of checkpoints is accurate though, so it found the files at least... progress 👍🏾

**Comment by Dok11** [comment]
Can you show files structure with model checkpoints and usage command?

**Comment by bckwalton** [comment]
Not currently at my machine, but the colab link has the commands and outputs I ran for generating progress. I believe it also has a directory print out there.
