### ISSUE TITLE
A question about using '--multi-gpus'

### ISSUE THREAD

**Issue by TomasZhang19** [lucidrains/lightweight-gan#75]
Dear author,
        I meet the following error message using '--multi-gpus'. 

default<./path/to/images>:   0%|          | 0/200000 [00:00<?, ?it/s]
default<./path/to/images>:   0%|          | 1/200000 [00:27<1526:51:39, 27.48s/it]
default<./path/to/images>:   0%|          | 4/200000 [00:35<497:33:29,  8.96s/it] 
Traceback (most recent call last):
  File "/home/y192235032/.conda/envs/LWGAN/bin/lightweight_gan", line 33, in <module>
    sys.exit(load_entry_point('lightweight-gan==0.18.1', 'console_scripts', 'lightweight_gan')())
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/lightweight_gan-0.18.1-py3.6.egg/lightweight_gan/cli.py", line 185, in main
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/lightweight_gan-0.18.1-py3.6.egg/lightweight_gan/cli.py", line 176, in train_from_folder
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/lightweight_gan-0.18.1-py3.6.egg/lightweight_gan/cli.py", line 66, in run_training
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/lightweight_gan-0.18.1-py3.6.egg/lightweight_gan/lightweight_gan.py", line 1104, in train
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/y192235032/.conda/envs/LWGAN/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 258.00 MiB (GPU 0; 9.78 GiB total capacity; 7.80 GiB already allocated; 76.31 MiB free; 8.46 GiB reserved in total by PyTorch)
/home/y192235032/.lsbatch/1616548331.17230.shell: 19: /home/y192235032/.lsbatch/1616548331.17230.shell: --multi-gpus: not found

The command I use is as following:
CUDA_VISIBLE_DEVICES=2,3,6,7  lightweight_gan \
    --data ./path/to/images \
    --image-size 1024 \
    --name default \
    --batch-size 16 \
    --gradient-accumulate-every 4 \
    --num-train-steps 200000 \
    --generate_types default
      --multi-gpus true

Could you please tell me how to solve the problem?

**Comment by deklesen** [comment]
No need to put "true" after the --multi-gpus flag. Also, your error message reads "RuntimeError: CUDA out of memory".
